name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  SKIP_DEPLOYMENT: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '10'
      - name: install server dependencies
        run: npm install
      - name: install client dependencies
        run: cd client && npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: cd client && npm run build
      - name: notify discord of failed build
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        if: failure()
        with:
          args: 'The build for commit `${{ github.sha }}` has failed'
      - name: test
        run: cd client && npm test -- --passWithNoTests
      - name: deploy
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: notify discord of successful deployment
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        if: success()
        with:
          args: 'A new version of Package viewer deployed to https://package-viewer-ypgl.onrender.com/'
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && env.SKIP_DEPLOYMENT == 'false' }}
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch